version: '1.0'

services:
  app:
    build:
      context: .
    command: python3 /app/infer_sd14.py
    volumes:
      - ./output:/output
      - ~/.aws/:/root/.aws:ro
    environment:
      - AWS_DEFAULT_REGION=
      - CRYPTOGRAPHY_DONT_BUILD_RUST=1
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_$KEY=AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - SQS_QUEUE_URL=
      - S3_BUCKET_NAME=
      - CLOUDFRONT_DOMAIN=
      - S3_REGION=
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
